### ISSUE TITLE
Use discover runner instead of homemade runtests.py

### ISSUE THREAD

**Issue by jezdez** [pydanny/django-admin2#318]
Django 1.6 and upwards ships with a new default test runner that uses unittest2's vastly improved test coverage. I've released django-discover-runner as a backport.

This basically allows you to use `django-admin.py test djadmin2 blog` as well as `django-admin.py test djadmin2.tests.test_core.Admin2Test` and of course allows you to drop the awful anti-pattern of star imports in `test` init modules.

**Comment by galuszkak** [comment]
@jezdez this is possible with py.test right now (with #403). I think we should close this 👍 . Thanks!

**Comment by jezdez** [comment]
Woah, blast from the past. Thanks for closing this @galuszkak!
