### ISSUE TITLE
Use of unicode(str).

### ISSUE THREAD

**Issue by douglasmiranda** [pydanny/django-admin2#390]
We've been using the unicode casting. Since there is no unicode() in python 3, should we be worried right now, or let's leave that for the future?
 
![screenshot from 2013-12-01 03 54 10](https://f.cloud.github.com/assets/542013/1650045/d24d45b0-5a55-11e3-97c7-3dcf920c3c5a.png)

**Comment by galuszkak** [comment]
This is for now fixed. I think this should be close @andrewsmedina @pydanny
