### ISSUE TITLE
Applications (New in Django 1.7)

### ISSUE THREAD

**Issue by douglasmiranda** [pydanny/django-admin2#397]
Django (1.7) now allows you to have a application configuration class. We will use this new concept?

What do you guys think?

More info:
https://docs.djangoproject.com/en/dev/ref/applications/

**Comment by auvipy** [comment]
+1

**Comment by auvipy** [comment]
@galuszkak https://github.com/pydanny/django-admin2/blob/develop/djadmin2/apps.py this issue is solved already

**Comment by galuszkak** [comment]
Yes. Thanks @auvipy & @arthur-wsw !  Fixed with #431 .
