### ISSUE TITLE
Polls has no field named 'published_date'

### ISSUE THREAD

**Issue by nick-lehmann** [pydanny/django-admin2#398]
I tried out the example2 of this repo. This example should demonstrate the use of this module by creating a poll website. If I want to visit the admin site for manipulating the polls under 'http://localhost:8000/admin2/polls/poll/' I get the error message "Poll has no field named 'published_date'". Unfortunately, I can not find the term 'published_date in the directory using grep. How can I fix it?

**Comment by galuszkak** [comment]
This is fixed now. Could you close please @andrewsmedina ?
