### ISSUE TITLE
strange tox behaviour

### ISSUE THREAD

**Issue by montiniz** [pydanny/django-admin2#411]
after i upgrading my env to django 1.7.3 and removing tox dir from my project i ran tox. on django 1.7 tox envs started getting `ImportError: No module named related`. After checking whats installed in tox dir, found that django1.8a1 was installed. 
my tox.ini is at develop HEAD.
`[testenv:py27-dj1.7.x]
basepython=python2.7
deps =
    Django>=1.7,<1.8
    {[testenv]deps}`

if i change to `Django==1.7.3`, it installs corectly. 

don't think its django-admin2 issue though. 
can someone confirm this.

**Comment by galuszkak** [comment]
Yes, I fixed that here #410 . give me one day to finish that PR.

**Comment by galuszkak** [comment]
Sorry it took so long. I will be fixing this today.

**Comment by galuszkak** [comment]
This is fixed with #431
