### ISSUE TITLE
Update DRF to 3.x.x

### ISSUE THREAD

**Issue by auvipy** [pydanny/django-admin2#420]

**Comment by andrewsmedina** [comment]
@auvipy DRF is django-rest-framework?

**Comment by thedrow** [comment]
Yup.

**Comment by auvipy** [comment]
i was unable to use it with django 1.8.

**Comment by auvipy** [comment]
should use DRF 3.3+

**Comment by auvipy** [comment]
i will try to make a PR

**Comment by galuszkak** [comment]
What is minimal django version supported by DRF 3.3+ ? I think we made decision to support Django 1.6 and higher because of support of Python 3.

**Comment by auvipy** [comment]
django 1.6 do not receive security updates anymore. and 1.7 should be the min version supported

**Comment by auvipy** [comment]
now I think its OK to drop <1.8 support? I will be happy to send PR

**Comment by andrewsmedina** [comment]
I'm +1 to drop. These versions are deprecated by django team.

**Comment by galuszkak** [comment]
Fixed in #431
