### ISSUE TITLE
Django 1.8 issue

### ISSUE THREAD

**Issue by auvipy** [pydanny/django-admin2#421]
python manage.py migrate
/home/asif/Envs/agro/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

/home/asif/Envs/agro/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  return f(*args, **kwds)

/home/asif/Envs/agro/lib/python3.4/site-packages/djangorestframework-2.4.4-py3.4.egg/rest_framework/serializers.py:155: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.

/home/asif/Envs/agro/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)

/home/asif/Envs/agro/lib/python3.4/site-packages/django_admin2-0.6.1-py3.4.egg/djadmin2/models.py:28: RemovedInDjango19Warning: Model class djadmin2.models.LogEntry doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class LogEntry(models.Model):

Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles, djadmin2, floppyforms
  Apply all migrations: agroquest, sessions, contenttypes, admin, auth
Synchronizing apps without migrations:
  Creating tables...
    Creating table djadmin2_logentry
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
/home/asif/Envs/agro/lib/python3.4/site-packages/django_admin2-0.6.1-py3.4.egg/djadmin2/permissions.py:385: RemovedInDjango19Warning: django.db.models.get_models is deprecated.
  app_models = get_models(app)
Installed from master branch and the following output in terminal

/home/asif/Envs/agro/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

/home/asif/Envs/agro/lib/python3.4/functools.py:448: RemovedInDjango19Warning: The app_mod argument of get_models is deprecated.
  result = user_function(*args, **kwds)

**Comment by galuszkak** [comment]
Hi @auvipy !
Thanks for report, we will try to fix those warnings

**Comment by erayerdin** [comment]
I have the same issue too. Just saying.

**Comment by galuszkak** [comment]
Fixed with #431
