### ISSUE TITLE
Add Django 1.9 compatability

### ISSUE THREAD

**Issue by auvipy** [pydanny/django-admin2#425]

**Comment by galuszkak** [comment]
@auvipy we will added it when there will be release of django 1.9 stable. For now it's in beta.

**Comment by auvipy** [comment]
seems the maintainers do not have time to work on this project. I would love to work on django + DRF
version compatibility. [I am a co maintainer of drf-extensions, and helped upgrading drf-gis project]

Let me know which parts I need to work/you need contribution to make it compat with latest stable versions?

**Comment by pydanny** [comment]
@auvipy I think it's a difference between the maintainers having *free time* to work on django-admin2 and having *paid time* to work on this project. Unfortunately, I've yet to see a single firm or agency step up to provide *paid time* for this project. In the early days it was promised, but never materialized. Since my open source time is limited, I stepped back from this project once it became apparent how much of my open source time it consumed.

Part of that stepping back was also no longer reviewing pull requests. Those reviews take a lot of time, and are not as much fun as writing code. @galuszkak and @andrewsmedina stepped up, but I think they've come to realize that this project is a time sink that doesn't give back to the maintainer the same way other projects do.

For what it's worth, I've offered @galuszkak and @andrewsmedina to mark this project as unmaintained. They continued to volunteer their time, but I think other concerns have become more important to them. Which I respect and agree on 100%. django-admin2 is a sophisticated project, and one that does eat up a lot of time. You either put in a lot of time or you don't.

Therefore, unless someone can offer myself or them paid time on the project, even as part of a contract for something else, I'm going to mark this project as *unmaintained*. That means adding a message like this to the README:

> # This Project is Unsupported

> If you decide to use this project, be forewarned that support and patches will not be forthcoming at this time. Why?

> 1. The maintainers of this project are not working and have never worked professionally with django-admin2. 
> 2. The maintainers of this project have to triage their open source time to projects they use on a regular basis, or are paid to maintain. 

> If you want to pay the maintainers of this project to support it again, please contact @pydanny at pydanny@gmail.com.

**Comment by auvipy** [comment]
@pydanny I do agree to all your points. I do also have to spent my time to work on some open source project. I generally try to contribute to the projects which have some impact on my day to day works. Since I find this project very promising and want to see it alive for long, I do want to offer my time to maintain this project as a co-maintainer. If you think that make sense please let me know. :)

**Comment by galuszkak** [comment]
@auvipy django 1.9 was release just not long ago. As I said I still plan (It was 1,5 month when I declared this work) to add this funcionality. I plan to spend some time on Christmas holidays to work toward fixing those issues.

Most this year, was a little unplanned lack of time for open source as I spend more time to give time for open source community in Hackerspace Silesia. So sorry for dragging those issues longer than expected. (My last comments in this project was 1 month ago so not so long ago ;) )

**Comment by andrewsmedina** [comment]
@pydanny the django-admin2 is a so great project, and has a lot of potencial. I think that it is not necessary mark this project as unsupported.

And if we add full compatibility with Django 1.8 and 1.9 more people will use and contribute with this project.

I believe that I can work more in django-admin2. @galuszkak I can work on this issue, but before that I think that we can make all tests pass with Django 1.8, that I'm working on it right now.

@auvipy your contributions are very welcome. You can help send pull requests (http://django-admin2.readthedocs.org/en/latest/contributing.html) and if you want you can talk with us at https://gitter.im/pydanny/django-admin2

**Comment by galuszkak** [comment]
@andrewsmedina I'm not sure if you started working on issue if not then I started to get up to date with all tools. and continue my work in #410 . I see the biggest issue is that we lag behind really with rest framework and new django. I think we should solve them all in one pass so we can start development from something fresh to get up to speed.

**Comment by andrewsmedina** [comment]
@galuszkak I'm working on fix the tests on django 1.8

**Comment by galuszkak** [comment]
@andrewsmedina  I'm not sure where are you standing (can you push your work somewhere?). I created list of existing problems in tests in #410 I will be updating this list while moving on with fixing code tests.

**Comment by andrewsmedina** [comment]
@galuszkak the tests on Django 1.8 are broken. I believe that is not related with `django-rest-framework`. You can see the output from `tox -e py27-dj1.8.x` here: https://gist.github.com/andrewsmedina/c5ee574a5b5b2944b66d

I will enable Django 1.8 and 1.9 on travis-ci now.

**Comment by galuszkak** [comment]
@andrewsmedina please do it on different branch or your fork. Don't do this on develop branch. 

Yes they aren't related, I didn't stated otherwise ;), but sounds most of your errors are related to floppyforms not only django.

**Comment by galuszkak** [comment]
(I already did it on my rest-framework-fix branch so if you want you can take it)

**Comment by galuszkak** [comment]
@andrewsmedina also all work please do through pull requests so anyone can review changes.

**Comment by galuszkak** [comment]
I'm working from my fork, so this repository until everything is stable it's not affected. If you can @andrewsmedina, please revert those your changes and move it to different branch or fork.

**Comment by andrewsmedina** [comment]
@galuszkak I believe that the tests should be enabled on travis. But I will enable the travis `allow_failures` in 1.8 and 1.9 tests for now.

**Comment by galuszkak** [comment]
@andrewsmedina if you work on fork, or another branch you can change travis and it will catch changes only related to that branch so develop branch is never affected. 
Please revert those changes, so we have always stable develop branch, from which people can fork, and always work through PR it's really important :+1:

**Comment by andrewsmedina** [comment]
@galuszkak reverting. But the tests are already broken, run these tests is a way to show where the problem are. Without it everything looks ok, but it is not ok. =/

**Comment by andrewsmedina** [comment]
@galuszkak reverted

**Comment by galuszkak** [comment]
@andrewsmedina  no, they went fine see: https://travis-ci.org/pydanny/django-admin2 they all passed https://travis-ci.org/pydanny/django-admin2/builds/99833226
```========================= 212 passed in 13.92 seconds ==========================
```

**Comment by andrewsmedina** [comment]
@galuszkak the result was the same with allowed_failures enabled

**Comment by andrewsmedina** [comment]
@galuszkak I will create a PR with the django 1.8 and 1.9 tests and allow_failure enabled. What do you think to use gitter or irc to talk about it?

**Comment by galuszkak** [comment]
Fixed with #431

**Comment by auvipy** [comment]
time for a new release? :dancer:
