### ISSUE TITLE
Enhancement: Removing dependancy that matter only in theme

### ISSUE THREAD

**Issue by arthur-wsw** [pydanny/django-admin2#433]
I think floppyforms and django-crispy-forms has no need to be directly integrated in django-admin2 core as they can easily be set on project level. It should simplify maintaining django-admin2 and let more flexibility to final user in the choices of the app used for rendering forms.

I'm not saying whe should not care about django-admin2 compatibility with these app. I think we should also write part in documentation on how user could have them work in there projects.

What are you thinking of this ?

I will made some PR in this way, feel free to integrate them or not.

**Comment by galuszkak** [comment]
@arthur-wsw it's related to #343 👍

**Comment by arthur-wsw** [comment]
OK so i will work on this for a future PR
